### ISSUE TITLE
Kodi Matrix alpha 3

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.dvbviewer#102]
No DVBViewer addon on kodi matrix alpha 3.

**Comment by ghost** [comment]
No DVBViewer addon on kodi repository. If I try to install v 7.1.0 from https://jenkins.kodi.tv/view/All/job/kodi-pvr/job/pvr.dvbviewer/job/Matrix/ I get  "the dependency on kodi.binary.instance.inputstream version 3.0.1 could not be satisfied" error.

**Comment by phunkyfish** [comment]
Can you try the latest kodi beta and see if there is an add-on available then?

**Comment by ghost** [comment]
So far, so good. Thanks a lot!
