### ISSUE TITLE
Better description of project at README.md

### ISSUE THREAD

**Issue by narcisgarcia** [kodi-pvr/pvr.dvbviewer#103]
Please add more clear details about what dvbviewer is and does, and what role it plays around PVR clients/servers.
What is required for.

**Comment by phunkyfish** [comment]
https://kodi.wiki/view/Add-on:DVBViewer_Client

**Comment by narcisgarcia** [comment]
Please add a linked phrase as "More details in Kodi Wiki" just in description paragraph.

**Comment by phunkyfish** [comment]
PRs welcome

**Comment by narcisgarcia** [comment]
PR =?

**Comment by phunkyfish** [comment]
A pull request for the GitHub repo to make the change you would like.
