### ISSUE TITLE
EPG data no longer transfered

### ISSUE THREAD

**Issue by payback007** [kodi-pvr/pvr.dvbviewer#141]
Hi,

after reset of EPG data due to some missing data now all EPG data is gone. Reload of EPG doesn't work. Tested this on two different systems with the same result. All EPG data is available in dvbviewer webpage and also in the dvbviewer itselt.

Kodi: v19.3
dvbviewer plugin: v19.0.2
dvbviewer: 7.2.0
dvbviewer media server: 3.2.0
client: win10 or osx

Updated all dvbviewer and media server also to latest patch level. Any idea why EPG data is suddenly gone and can't be reloaded?

**Comment by phunkyfish** [comment]
I don't know why this is happening but have you tried to delete all PVR data?

**Comment by payback007** [comment]
What do you exactle mean with deleting all?

- I deleted all EPG data
- I deleted DVBviewer addon and reinstalled the dvbviewer addon

Result is always the same: no EPG data

**Comment by phunkyfish** [comment]
If you go to PVR settings in Kodi you should have an option to clear all data.

**Comment by manuelm** [comment]
See https://forum.kodi.tv/showthread.php?tid=366719&pid=3083434#pid3083434

**Comment by payback007** [comment]
thank you very much for the fast feedback! the beta-version did it!
