### ISSUE TITLE
Feature request: dvbviewer connection SATIP also over tcp protocol

### ISSUE THREAD

**Issue by michael7633** [kodi-pvr/pvr.dvbviewer#147]
Hello Team,

I do face issues with udp connections between dvbviewer media server and pvr.dvbviewr client.
I don't see those issues using the original dvbviewer client using tcp.
It would be great if one could choose between udp and tcp just like you can using the original dvbviewer client.

Greetings from Vienna ;-)
Michael

**Comment by manuelm** [comment]
The PVR is always using TCP. It's using the official supported API. The UDP protocol is private to the dvbviewer client and not supported. However whatever your issues is I doubt it's related to UDP vs TCP.
