### ISSUE TITLE
Timeshift buffer path can't be set, using an existing folder/directory

### ISSUE THREAD

**Issue by J-Peters** [kodi-pvr/pvr.dvbviewer#15]
Hi,

I am using Kodi 14.2 Helix with DVBViewer Client 1.9.24, DVBViewer Pro Recording Service 1.31.0.0 Beta (works properly, Win 7 Pro 64 SP1, TechniSat CableStar Combo HD CI, AzureWave Driver DTV USB TV-Box 7070).

Under "Settings > Advanced" one can enter a Timeshift buffer path, double click on the text "special://userdata/addon_data/pvr.dvbviewer". But this does NOT offer folders or paths for selecting one. Instead, you can create a new folder manually, but NOT every path will be accepted as expected:

1st example: D:\Users\Public\TVTimeShift
2nd example: \\<Computername>\Public\TVTimeShift (means an existing shared network directory/path)

The error message Pops up: <translated from German> "This path can't be created! Please ensure that the selected folder is not write-protected and the new path name is valid".

How to set a Timeshift buffer path, using an existing folder or shared network directory?

Many thanks in advance, and kind regards,
J-Peters

**Comment by manuelm** [comment]
This is a duplicate of https://github.com/manuelm/pvr.dvbviewer/issues/3
I'm lacking permissions, so someone else please close this in my behalf.
