### ISSUE TITLE
Deleting recording in progress => recording files will not be deleted from HDD

### ISSUE THREAD

**Issue by DankoHR** [kodi-pvr/pvr.dvbviewer#32]
Hello,
i encountered an issue when trying to delete a recording in progress. When deleting a active recording within Kodi, it gets deleted in DB of DVBViewer but the recording file on HDD does not get deleted. This issue only appears when deleting a recording that is in progress. When deleting finished recordings the files on HDD get deleted also properly.
Also when deleting a running recording over recording service web interface it gets deleted properly on HDD. Therfore i assume it has to be an issue releated to the DVBViewer Kodi addon.

I have reproduced this behaviour with OpenElec (latest x86 stable version) and also with Kodi v16.0  running on Windows.

**Comment by manuelm** [comment]
I doubt this is an issue in the pvr. The pvr is just issuing http calls to the webinterface / RS API. But I will try to reproduce this this evening.

**Comment by manuelm** [comment]
I can confirm the issue. The PVR is using this API call: http://en.dvbviewer.tv/wiki/Recording_Service_API#Delete_recording

So it's a RS bug.

**Comment by manuelm** [comment]
I've just reported the bug to the dvbviewer forum.

**Comment by DankoHR** [comment]
Okay, thank you for the quick reply and for reporting it to dvbviewer forum.

**Comment by manuelm** [comment]
From RS 1.33 changelog:
> If `/api/recdelete` cannot delete an existing recording because it is used somewhere else, the corresponding database entry is not deleted either (previously it was removed so the file could not be referenced anymore). The API now returns a “423 Locked” status code in this case.

However checking the http statuscode is still missing.

**Comment by manuelm** [comment]
This issue was moved to manuelm/pvr.dvbviewer#10

**Comment by manuelm** [comment]
Issue moved to new repo. This one will be closed.
