### ISSUE TITLE
Would it be possible to incorporate transcoding by textfield for the profile

### ISSUE THREAD

**Issue by Vlaves** [kodi-pvr/pvr.dvbviewer#37]
As we spoke here http://forum.kodi.tv/showthread.php?tid=271025&pid=2319597#pid2319597 maybe it is possible to add transcoding with that textfield.
Thanks a lot for your work :)

**Comment by Vlaves** [comment]
Any chance to get this implemented fro Kodi 17?

**Comment by manuelm** [comment]
Kodi 17 is already in feature freeze (beta state). So I'm sorry, this has to wait a little longer.

**Comment by Vlaves** [comment]
Too bad :( Was waiting for Kodi 17 just for that feature :( Any chance to get it implemented and compile the Addon seperately? :)

**Comment by Jalle19** [comment]
@manuelm addons aren't blocked by the feature freeze, that's why they're addons

**Comment by manuelm** [comment]
@Jalle19 Has this changed with Kodi 17? I was under the impression that PVR updates are only shipped/rolled out with general Kodi releases/updates

**Comment by wsnipex** [comment]
the problem is that part from ubuntu linux where I package them all separately, platforms still build and package addons together with kodi itself(for the lack of a proper repo for binary addons).

That means: You can update the addon, but it will only hit stable kodi on windows, android, OSX whenever kodi gets a minor release or someone decides to rebuild stable for whatever reason.

That said, its up to the addon maintainers to decide to pull features, kodi's feature freeze doesn't stop you here.

**Comment by Vlaves** [comment]
@wsnipex So if I understand it correctly, if that change would be incorporated now, the next Beta or RC of Kodi 17 would have it integrated then (new compile)?

**Comment by wsnipex** [comment]
correct

**Comment by Vlaves** [comment]
@manuelm Would it in this case den be possible for you to incorporate this feature, that would really be great. Thanks a lot in advance.

**Comment by manuelm** [comment]
@Vlaves Would you mind testing the transcoding support?

**Comment by Vlaves** [comment]
@manuelm would not mind at all. Just that I only use Kodi on Android (Fire TV2) so I can't compile it myself. But if I get an apk provided, I will test for sure :)

**Comment by manuelm** [comment]
Try https://manuel.mausz.at/coding/kodi/2.4.4/pvr.dvbviewer-android-arm.zip

Not sure if it'll load. It's been at least 2 years since I've tested my android crosstool chain for Kodi.

**Comment by Vlaves** [comment]
Thanks will try it asap :)

**Comment by manuelm** [comment]
@Vlaves ping

**Comment by Vlaves** [comment]
@manuelm Sorry my Server Hardware is striking, DVB-Card died, waiting for new one I ordered to arrive, will get back as soon as it is up and running again, sorry for the delay...believe me it is THE feature I've been waiting for, so will test asap...
