### ISSUE TITLE
Addon Update 2.3.1 did not finally solved timer issue

### ISSUE THREAD

**Issue by 2Hide** [kodi-pvr/pvr.dvbviewer#38]
As described here http://forum.kodi.tv/showthread.php?tid=258416&page=2 the UTF-8 problem is now solved. Thanks.

But Kodi still throws an exception when the timer list is not empty. Here is the relevant log:
18:32:57  17.911835 T:1769730976   DEBUG: CurlFile::Open(0x73cf0200) http://192.168.0.4:8088/api/timerlist.html?utf8=2
18:32:57  17.993204 T:1769730976   DEBUG: SECTION:UnloadDll(/usr/lib/kodi/addons/pvr.dvbviewer/pvr.dvbviewer.so.2.3.1)
18:32:57  17.995932 T:1769730976   ERROR: ADDON: Dll DVBViewer Client, throws an exception 'basic_string::_S_construct null not valid' during m_pDll->Create. Contact developer 'A600, Manuel Mausz' with bug reports
18:32:57  17.997324 T:1769730976   ERROR: UpdateAddons - failed to create add-on DVBViewer Client, status = 4

**Comment by manuelm** [comment]
Thank you very much for reporting. Should be fixed.

I guess it's time to start using K* on a daily basis. The bug was rather obvious.

**Comment by 2Hide** [comment]
It is now working as expected. Thanks.
