### ISSUE TITLE
Kodi 17 & pvr.dvbviewer 2.4.3 & recording service 1.30.1.0 does not work!

### ISSUE THREAD

**Issue by deathaxe** [kodi-pvr/pvr.dvbviewer#42]
With Kodi 17 beta 2 Live-TV support is broken on my system. I can't activate the pvr.dvbviewer addon.

Kodi.log shows

```
11:50:53 T:3320  NOTICE: AddOnLog: DVBViewer Client: Checking backend version...
11:50:53 T:3320  NOTICE: AddOnLog: DVBViewer Client: Version: 18743552
11:50:53 T:3320   ERROR: CCurlFile::Open failed with code 404 for http://127.0.0.1:8089/api/status2.html
11:50:53 T:3320   ERROR: AddOnLog: DVBViewer Client: Unable to get backend status. Error: Error document empty.
11:50:53 T:3320   ERROR: ADDON: Dll DVBViewer Client - Client returned bad status (1) from Create and is not usable
11:50:57 T:3320   ERROR: PVR::CPVRClients::UpdateAddons - failed to create add-on DVBViewer Client, status = 1
```

By changing the status URL to http://127.0.0.1:8089/api/status.html Live-TV works fine again.

```
bool Dvb::UpdateBackendStatus(bool updateSettings)
{
  const std::string &req = GetHttpXML(BuildURL("api/status.html"));

  TiXmlDocument doc;
  doc.Parse(req.c_str());
...
```

As I never tried another version of recording service than 1.30.1.0 my question now is whether _/api/status2.html_ is a typing error or depends the URL from recording service version?

**Comment by manuelm** [comment]
`api/status.html` is deprecated since 1.30.1. See http://www.dvbviewer.tv/forum/topic/19629-recording-service-beta/?p=431016 + https://github.com/kodi-pvr/pvr.dvbviewer/commit/5bbbafa36c1a4a4cc8ad3fcdef6d681ffc494497

Are you sure you're running RS 1.30.1?

I'll leave this bug report open as the URL change broke the detection of old RS versions.

**Comment by deathaxe** [comment]
Wow, very fast answer. 

Yes I am running 1.30.1 for years now. Maybe it's still a beta built. If the URL changed, I think it was a good idea to check version and load from eigher /api/status.html or /api/status2.html just to keep compatibility with older versions. The integer value of recording service version is printed in Kodi.log as received from the /api/version.html. If I type 127.0.0.1:8089/api/status.html everything is fine. status2.html is not found (404)

**Comment by manuelm** [comment]
Yeah, please test upgrading your RS version. I'll fix the version detection. But in general I don't support older RS versions.

**Comment by deathaxe** [comment]
Tried recording service 1.32 but for some yet unknown reason, it does not start, so I need to keep using 1.30.1 with a modified version of your addon for now.

**Comment by manuelm** [comment]
So I just checked this and I'm doing a version check *before* pulling any data. Nothing to fix here.

From the first output the version check says you're running 1.30.1.0, however `api/status2.html` is not available, which is contrary to the RS changelog. I'll just close this because if you're running an inofficial built you're on your own.

**Comment by 5anjar** [comment]
i have the same exact issue
everything was working fine on the previous version 
how can i change status2  to status ?

 
22:51:47.380 T:30104 WARNING: PVR::CPVRClient::GetAddonProperties - Addon DVBViewer:127.0.0.1 (Not connected!) does not support timer types. It will work, but not benefit from the timer features introduced with PVR Addon API 2.0.0
22:51:47.390 T:58436  NOTICE: AddOnLog: DVBViewer Client: Checking backend version...
22:51:47.390 T:58436  NOTICE: AddOnLog: DVBViewer Client: Version: 18743552
22:51:47.391 T:58436   ERROR: CCurlFile::Open failed with code 404 for http://127.0.0.1:8089/api/status2.html

**Comment by manuelm** [comment]
The RS version check is incorrect. I forgot to bump it. You are running RS 1.30 but need to be running 1.31 or above.

**Comment by deathaxe** [comment]
> how can i change status2 to status ?

HexEditor :-)

**Comment by 5anjar** [comment]
First id like to thank you for your quick response :) 
I downloaded the rs 1.31 as suggested
I got it working on the local machine but not the remote machine 
My remote machine is a preinstalled kodi android box i cant change the kodi on it 
The local machine runs kodi 17 

Now i think i wilk revert it bak to a previous version 
Am not a programmer am mechanical engineer :) 

Ithink the dvb viewer client for kodi shoud have a check box ( if u r using rs 1.30 or older

**Comment by 5anjar** [comment]
On which file should i use the hex editor 
Can you expedite

**Comment by deathaxe** [comment]
I am pretty sure the dev will hate me for this post but he chose not to support older versions of recording service.

I used TinyHexer as I didn't want to setup a developement environment for such a trivial change.

Just search for `status2.html` and remove the 2 and add a hex 00 after `.html` for proper 0-termination.

**CAUTION:** Make sure not to move any byte of the code or this plugin will crash!

### before

![dvbviewer_old](https://cloud.githubusercontent.com/assets/16542113/24524032/7aab5320-1595-11e7-9530-a281720d79c9.png)

### after

![dvbviewer](https://cloud.githubusercontent.com/assets/16542113/24523914/f9e9794c-1594-11e7-9026-595cb67fe3a6.png)

**Comment by 5anjar** [comment]
thnk you alot its working like a charm 
i just got the chance to do it , you were very helpful

**Comment by joselete25** [comment]
Hi
I'm new here and my english is not very good
I have a question. The status2 for status in pvr.dvbviewer in pc is already done. I have osmc in my raspberry and it has the same error but here I don't have pvr.dvbviewer.dll.
what am I supposed to do?
thank you

**Comment by Jalle19** [comment]
Pastebin a debug log from our Raspberry Pi.

**Comment by joselete25** [comment]
I don't know how to copy the log of oscm. I took a picture
Thank you for answering
![img_2419](https://cloud.githubusercontent.com/assets/28857638/26302322/209c8a02-3ee4-11e7-80bf-f99950d6ef0b.JPG)

**Comment by joselete25** [comment]
It's already working
thank you Jalle19

**Comment by manuelm** [comment]
With https://github.com/kodi-pvr/pvr.dvbviewer/commit/146cf89515dd0417fdb71a61ba9eef9d7b64ccf4 the required RS version got bumped to 1.33.2 (Kodi Leia)
