### ISSUE TITLE
Error building  pvr.dvbviewer  with clang: No type named in namespace

### ISSUE THREAD

**Issue by slacka** [kodi-pvr/pvr.dvbviewer#43]
Building  pvr.dvbviewer  with clang results in:

`DvbData.h:234:31: error: no type named 'function' in namespace 'std'`

Full log:
http://clang.debian.net/logs/2016-08-30/kodi-pvr-dvbviewer_1.11.11+git20160220-1_unstable_clang.log

**Comment by manuelm** [comment]
Hmm, apparently `-std=c++11 -stdlib=libc++` is missing. Looks like a (kodi) build system issue. It definitely worked a while ago: https://travis-ci.org/kodi-pvr/pvr.dvbviewer/jobs/153858685

**Comment by manuelm** [comment]
Looks like a build system error at your side.

https://anonscm.debian.org/cgit/pkg-multimedia/kodi-pvr-dvbviewer.git/tree/CMakeLists.txt#n10 includes the kodi package. 

The kodi package adds `CXX11_SWITCH` to our cxx flags at https://anonscm.debian.org/cgit/pkg-multimedia/kodi.git/tree/project/cmake/kodi-config.cmake.in#n16

`CXX11_SWITCH` gets set at https://anonscm.debian.org/cgit/pkg-multimedia/kodi.git/tree/project/cmake/scripts/common/prepare-env.cmake#n55

**Comment by Jalle19** [comment]
Travis seems to be able to build with Clang, at least last time I checked?
