### ISSUE TITLE
Replace deprecated getfavourites

### ISSUE THREAD

**Issue by CiNcH83** [kodi-pvr/pvr.dvbviewer#47]
... with getchannelsxml, see [here for an explanation](http://en.dvbviewer.tv/wiki/Recording_Service_web_API#getchannelsxml).

**Comment by manuelm** [comment]
This issue was moved to manuelm/pvr.dvbviewer#12

**Comment by manuelm** [comment]
Issue moved to new repo. This one will be closed.
