### ISSUE TITLE
Should the 2.4.7 release actually be 2.4.7-Krypton? 

### ISSUE THREAD

**Issue by candrews** [kodi-pvr/pvr.dvbviewer#52]
https://github.com/kodi-pvr/pvr.dvbviewer/releases/tag/2.4.7 was just released.

However, it looks like it should be 2.4.7-Krypton to be like the previous release: https://github.com/kodi-pvr/pvr.dvbviewer/releases/tag/2.4.6-Krypton

**Comment by manuelm** [comment]
Why? It's no ambiguous anyway. Every major Kodi causes the PVR's major or minor version number getting bumped. So pvr.dvbviewer for Kodi 18 already is 3.0.x

**Comment by candrews** [comment]
It doesn't really matter to me... I just noticed it was inconsistent so I wanted to ask.

**Comment by manuelm** [comment]
Ok. Just for the records: The `2.4.6-Krypton` tag has been created by a Kodi-Team member as part of an automated or semi-automated task before the release.

**Comment by MartijnKaijser** [comment]
@manuelm that was explicitly done to clearly show the difference between v17 and v18 tagged version. But hey it's your addon and up to you whatever to do with this.

Also we want to get rid of the https://github.com/kodi-pvr/  repo so if you want to continue your development in your own repo/location just let us know.

**Comment by manuelm** [comment]
> that was explicitly done to clearly show the difference between v17 and v18 tagged version.

hmm, some other PVRs don't have that kind of tags. e.g vdr.vnsi or hts.

> We will likely also start requiring tags for "master" at some point.

Sure, no problem.

> Also we want to get rid of the https://github.com/kodi-pvr/ repo so if you want to continue your development in your own repo/location just let us know.

Well, I can't stop you. But what about minor ABI changes? In the past you guys have at least always updated the signatures.

**Comment by MartijnKaijser** [comment]
That will fall upon the maintainers of the addons to keep up with changes.
