### ISSUE TITLE
Timeshift Buffer isn't deleted after stop

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [kodi-pvr/pvr.dvbviewer#56]
Hey,
i tried latest Plugin with Timeshift Path on a NFS ... buffer.ts isn't deleted after stopping playback.

**Comment by manuelm** [comment]
Bufferfile won't get deleted, only truncated (see https://github.com/manuelm/pvr.dvbviewer/blob/master/src/TimeshiftBuffer.cpp#L31).

Also this is the wrong repo. Please head over to https://github.com/manuelm/pvr.dvbviewer/. Thanks.
