### ISSUE TITLE
iptv no epg

### ISSUE THREAD

**Issue by dellas60** [kodi-pvr/pvr.dvbviewer#66]
when i'm on dvbviewer there's epg from iptv(vu+),but on kodi with your great addon there is no epg

**Comment by manuelm** [comment]
The EPG get's pulled using the RS API. Do you see EPG entries in the RS webinterface or by visiting http://<rs_ip>:8089/api/epg.html ?

If you use some external data feed make sure to insert the data into the RS. But I'm not sure if that's possible.

**Comment by dellas60** [comment]
i use dms 2.0.2,and yes i see epg on dms web interface  from dvbs and iptv,but on kodi i can see only epg from dvbs channel

**Comment by manuelm** [comment]
Which Kodi or PVR version?

**Comment by dellas60** [comment]
kodi 17.3 and kodi 18 alpha(milhouse)/dvbviewer 3.0.5

**Comment by manuelm** [comment]
So you're missing EPG in both Kodi versions?

**Comment by dellas60** [comment]
no,since the dms 2.0.0. the problem is appear only for iptv there is no problem with dvb s epg

**Comment by manuelm** [comment]
I assume DMS doesn't export the EPG for IPTV. For further debugging you can either look at the output from `http://<rs_ip>:8089/api/epg.html?lvl=2&channel=<epg_id>` yourself, the value for `epg_id` can be fetched from `http://<rs_ip>:8089/api/getchannelsxml.html?fav=1&subchannels=1&upnp=1&logo=1`

or create + pastebin a Kodi debug log which allows me to extract you the url.

**Comment by dellas60** [comment]
How to create + pastebin a Kodi debug log

**Comment by manuelm** [comment]
See http://kodi.wiki/view/Log_file/Easy

**Comment by dellas60** [comment]
thanks

**Comment by dellas60** [comment]
https://gist.github.com/anonymous/0820acc6aad35f36702bb2fe9692a0d8

**Comment by dellas60** [comment]
when i put epg id there is no epg on iptv channel i get "<epg Ver="2"/>"

**Comment by manuelm** [comment]
Well, you have a lot of channels defined. Grepping for `Loaded x EPG entries for channel ...` doesn't yield a single EPG entry. All your channels have 0 EPG entries.

Can you name me a channel which has EPG in the DMS webinterface? I'm not talking about any EPG in the dvbviewer application.

**Comment by dellas60** [comment]
MBC 1 on divers group has epg (dvbs),but on mbc group has no epg (iptv)

**Comment by manuelm** [comment]
> MBC 1 on divers group has epg (dvbs),but on mbc group has no epg (iptv)

RS API says `NILSAT/MBC 1` and `mbc/MBC 1` doesn't have any EPG:
```
[...]
15:59:41.850 T:139713155405568   DEBUG: CurlFile::Open(0x7f10e0005da0) http://192.168.1.110:8089/api/epg.html?lvl=2&channel=571746048281330&start=42906.624769&end=42910.624769
15:59:41.850 T:139713155405568    INFO: AddOnLog: DVBViewer Client: Loaded 0 EPG entries for channel 'MBC 1'
[...]
15:59:42.525 T:139713155405568   DEBUG: CurlFile::Open(0x7f10e0005e00) http://192.168.1.110:8089/api/epg.html?lvl=2&channel=2073305426052460&start=42906.624769&end=42910.624769
15:59:42.525 T:139713155405568    INFO: AddOnLog: DVBViewer Client: Loaded 0 EPG entries for channel 'MBC 1'
[...]
```

Can you provide a screenshot which clearly shows that `NILSAT/MBC 1` or `mbc/MBC 1` actually has EPG? I still doubt that.

PS: Debugging with a few channels is a lot easier than with 8512. So if you want to further diagnose the problem (after showing me the screenshot) I kindly ask you to reduce your channels and make their names unique.

**Comment by dellas60** [comment]
with mbc only
https://gist.github.com/dellas60/b63bde872d29616f892706e87c7ab068

**Comment by manuelm** [comment]
The new log doesn't contain any new information.

> Can you provide a screenshot which clearly shows that `NILSAT/MBC 1` or `mbc/MBC 1` actually has EPG? I still doubt that.

**Comment by dellas60** [comment]
![screenshot001](https://user-images.githubusercontent.com/29574213/27403964-511917de-56c4-11e7-8d91-4392859511b3.png)
![screenshot002](https://user-images.githubusercontent.com/29574213/27404015-76e4e9d4-56c4-11e7-9068-32bbb9be1e83.png)

**Comment by manuelm** [comment]
I'm not asking about screenshots from Kodi or from the Dvbviewer application. I'm asking about screenshots from the DMS webinterface which shows the missing EPG.

**Comment by dellas60** [comment]
![capture](https://user-images.githubusercontent.com/29574213/27405071-1a67fdaa-56c8-11e7-8717-de9e42041e46.JPG)
![capture2](https://user-images.githubusercontent.com/29574213/27405072-1a70d768-56c8-11e7-835a-6e22040be04e.JPG)

**Comment by manuelm** [comment]
Thank you. I'll ask in the dvbviewer forum about your issue. I still don't see anything wrong on the PVR side.

One last thing. Can you pastebin me your channel list? The reduced one would be prefered. You can export it from the RS API endpoint: http://<rs_ip>:8089/api/getchannelsxml.html?subchannels=1&logo=1

**Comment by manuelm** [comment]
What's the output of: http://192.168.1.110:8089/api/epg.html?lvl=2&channel=2073305426052460&start=42906.729329&end=42910.729329 ? Is it empty/`<epg Ver="2"/>` or do you actually see some entries?

Also if you happen to have an android device you can test the dvbviewer app (it's free) and verify you actually have EPG entries there. It's using the same API as the PVR.

**Comment by dellas60** [comment]
yes  empty,and for android app same problem no epg for iptv

**Comment by manuelm** [comment]
Ok, thank you. I've asked about your issue in an internal dvbviewer forum. I assume the DMS webinterface has either access to some extra EPG which the API doesn't have or it's just a bug. We'll see.

**Comment by dellas60** [comment]
https://gist.github.com/dellas60/fdeb7662781d7e7458a994b3b738a961

**Comment by manuelm** [comment]
Which tool are you using to import the (external) EPG for the IPTV channels?

**Comment by manuelm** [comment]
Tjod from the dvbviewer team asked what kind of channel your IPTV channels are. Do you have added them as `TS streams` or as `DVB IPTV`? You can check their type in the channellist editor. If they are of type `DVB IPTV` it's the best to remove them and add them as TS streams again.

**Comment by dellas60** [comment]
Yes the format is ts streams.and no epg

**Comment by dellas60** [comment]
There is no tool,dbbviewer scan m3u channel list from vu+ (enigma2), and put epg auto without tool

**Comment by manuelm** [comment]
According to Griga from the DVBViewer team your vu+ device might send the EPG as part of the TS-stream and the DMS webinterface is doing a fallback to the DVB-S EPGID schema if no EPG has been found. Right know this is nothing a DMS API consumer like my PVR or the android app can do.

**Comment by dellas60** [comment]
Ok,thank you

**Comment by manuelm** [comment]
Griga has implemented a fix for this in the DMS. You might contact him for a beta test or just wait for the next release.

**Comment by dellas60** [comment]
Thank you,you are the best.but he can give me beta test.

**Comment by manuelm** [comment]
Closing this. It's fixed in DMS
