### ISSUE TITLE
Undefined symbol: GetStreamTimes

### ISSUE THREAD

**Issue by kafisc** [kodi-pvr/pvr.dvbviewer#68]
Kodi (18.0-ALPHA1 Git:36b44e4). Platform: Linux x86 64-bit (Milhouse Generic #0813)
Latest working Version: Milhouse Generic #0803

Log:
ERROR: Unable to load /usr/lib/kodi/addons/pvr.dvbviewer/pvr.dvbviewer.so.3.1.0, reason: /usr/lib/kodi/addons/pvr.dvbviewer/pvr.dvbviewer.so.3.1.0: undefined symbol: GetStreamTimes

**Comment by Jalle19** [comment]
@manuelm can you implement the new API methods?

**Comment by manuelm** [comment]
Yep. Was waiting for 5.6.0 to get merged and the nightlys to build

**Comment by manuelm** [comment]
fixed. https://github.com/manuelm/pvr.dvbviewer/commit/1f31807118d2df7504774ad0db50370d7aaf386d
