### ISSUE TITLE
Matrix nightlies crash since DVBViewer add-on 6.0.0 update

### ISSUE THREAD

**Issue by CiNcH83** [kodi-pvr/pvr.dvbviewer#91]
Since updating to DVBViewer add-on 6.0.0, Matrix nightlies crash during startup. Am attaching a logcat with the crash report.

[LOG](https://www.dropbox.com/s/hq9ax7btagcpy1e/kodi_pvr_crash.txt?dl=1)

**Comment by phunkyfish** [comment]
I'm not seeing a reference to DVBViewer in the crash report. Although if it's on startup maybe I can check myself.

**Comment by manuelm** [comment]
@phunkyfish 
```
--------- beginning of crash
06-23 18:22:13.160  7121 10044 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 10044 (Thread-3)
06-23 18:22:13.161  7121  9895 E Kodi    : 2020-06-23 18:22:13.161 T:9895    ERROR <general>: GetAddonProperties: Add-on 'unknown' returned an error: server error
```

@CiNcH83 I'm fairly busy with private and work-life. Got a bunch of extra jobs during corona and my son is demanding more of my spare time. So although I'm not that active anymore I haven't forgotten about the addon and I will look into this.

**Comment by phunkyfish** [comment]
It's ok, I found the issue, something missing in C++ API rework. PR on its way. The addon starts once this PR is applied.

**Comment by phunkyfish** [comment]
https://github.com/kodi-pvr/pvr.dvbviewer/pull/92

**Comment by manuelm** [comment]
So it looks like Kodi doesn't pull the channels from the plugin although the plugin changed the state to `CONNECTED` + called `TriggerChannelUpdate`. Still investigating.

**Comment by manuelm** [comment]
6.0.4 should be running again

**Comment by Shamshala** [comment]
Don't know how about others but v6.0.4 crashes the whole Kodi at the start for me.
The last line what i see in debug is:
`2020-07-16 06:03:10.536 T:8260     INFO <general>: AddOnLog: pvr.dvbviewer: Trying to connect to the backend server...`

v6.0.1 simply didn't work with only `Server is not responding propery` error and `user`/`pass` error in debug log.

**Comment by Shamshala** [comment]
Don't know how about others but v6.0.4 crashes the whole Kodi at every launch for me.
I managed to disable the addon, here is debug log after enabling:
[kodi.log](https://github.com/kodi-pvr/pvr.dvbviewer/files/4929638/kodi.log)

v6.0.1 simply didn't work with only `Server is not responding properly` error and `user`/`pass` error in debug log.

**Comment by manuelm** [comment]
The follow up crash is handled in https://github.com/manuelm/pvr.dvbviewer/issues/45. Although I cant reproduce it yet.
